PowerNew/PowerNew/Controllers/Blog/ArticleInfo/ArticleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PowerNew.Bll;
using PowerNew.Common;

namespace PowerNew.Controllers
{
    public partial class ArticleInfoController : BaseController
    {
        // GET: ArticleType
        public ActionResult Index(QueryArticleInfo query)
        {
            var list = ArticleInfoManager.GetInstance().GetPageList(query);
            ViewBag.Param = query;
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            var model = ArticleInfoManager.GetInstance().GetModel(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var item = ArticleInfoManager.GetInstance().SelectOne(m => m.id == id && m.isdelete == false);
                if (item == null)
                {
                    return Json(new { state = 1, msg = "未找到该条纪录," });
                }
                item.isdelete = true;
                item.updateid = Convert.ToInt32(Session["userid"]);
                item.updatetime = DateTime.Now;
                ArticleInfoManager.GetInstance().Update(item);
                ArticleInfoManager.GetInstance().Save();
                return Json(new { state = 0, msg = "删除成功" });
            }
            catch (System.Exception ex)
            {
                LogHelper.log.Error(ex.Message);
                return Json(new { state = 1, msg = ex.Message });
            }
        }
    }
}

PowerNew/PowerNew/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Web;
using System.Web.Mvc;
using PowerNew.Common;

namespace PowerNew.Controllers
{
    public class FileController : Controller
    {
        private string StorageRoot
        {
            get
            {
                var rootPath = Server.MapPath("~/Upload/Files");
                var savePath = GetSavePath(rootPath);
                return savePath;
            }
        }

        [HttpPost]
        public ActionResult UploadFiles()
        {
            var r = new List<ViewDataUploadFilesResult>();

            foreach (string file in Request.Files)
            {

                var statuses = new List<ViewDataUploadFilesResult>();
                var headers = Request.Headers;

                if (string.IsNullOrEmpty(headers["X-File-Name"]))
                {
                    UploadWholeFile(Request, statuses);
                }
                else
                {
                    UploadPartialFile(headers["X-File-Name"], Request, statuses);
                }

                JsonResult result = Json(statuses);
                result.ContentType = "text/plain";

                return result;
            }

            return Json(r);
        }

        private void UploadPartialFile(string fileName, HttpRequestBase request, List<ViewDataUploadFilesResult> statuses)
        {
            if (request.Files.Count != 1) throw new HttpRequestValidationException("Attempt to upload chunked file containing more than one fragment per request");
            var file = request.Files[0];
            var inputStream = file.InputStream;

            var saveName = this.GetSaveName(fileName);
            var fullName = Path.Combine(StorageRoot, saveName);

            using (var fs = new FileStream(fullName, FileMode.Append, FileAccess.Write))
            {
                var buffer = new byte[1024];

                var l = inputStream.Read(buffer, 0, 1024);
                while (l > 0)
                {
                    fs.Write(buffer, 0, l);
                    l = inputStream.Read(buffer, 0, 1024);
                }
                fs.Flush();
                fs.Close();
            }
            statuses.Add(new ViewDataUploadFilesResult()
            {
                openid = OpenHelper.CreateOpenId(),
                name = fileName,
                save_name = saveName,
                size = file.ContentLength,
                type = file.ContentType,
                url = GetHttpFileUrl(saveName),
                delete_url = Url.Action("Delete?id=" + saveName),
                delete_type = "GET",
            });
        }

        private void UploadWholeFile(HttpRequestBase request, List<ViewDataUploadFilesResult> statuses)
        {
            for (int i = 0; i < request.Files.Count; i++)
            {
                var file = request.Files[i];
                var saveName = this.GetSaveName(file.FileName);

                var fullPath = Path.Combine(StorageRoot, saveName);

                file.SaveAs(fullPath);

                statuses.Add(new ViewDataUploadFilesResult()
                {
                    openid = OpenHelper.CreateOpenId(),
                    name = file.FileName,
                    save_name = saveName,
                    size = file.ContentLength,
                    type = file.ContentType,
                    url = GetHttpFileUrl(saveName),
                    delete_url = Url.Action("Delete?id=" + saveName),
                    delete_type = "GET",
                });
            }
        }

        private string GetSavePath(string rootPath)
        {
            string path = Path.Combine(rootPath, DateTime.Now.Year.ToString(), DateTime.Now.ToString("MMdd"));
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            return path;
        }


        /// <summary>
        /// 文件夹命名与文件有关
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        private string GetSaveName(string fileName)
        {
            var savaName = DateTime.Now.ToString("yyyyMMdd") + new Random().Next(0, 999).ToString("D3") + "userid" + Convert.ToInt32(SessionHelper.GetSession("userid")) + Path.GetExtension(fileName);
            return savaName;
        }

        private string GetHttpFileUrl(string filename)
        {

            var url = "/Upload/Files/";
            var tmp = GetFilePath(filename).Replace("\\", "/");
            return url + tmp;

        }

        private string GetFilePath(string fileName)
        {
            var year = fileName.Substring(0, 4);
            var monthday = fileName.Substring(4, 4);
            return Path.Combine(year, monthday, fileName);
        }



        public ActionResult Download(string filePath, string downloadName)
        {
            if (System.IO.File.Exists(filePath))
            {
                byte[] bytes = System.IO.File.ReadAllBytes(filePath);

                //解决不同浏览器乱码问题
                HttpBrowserCapabilitiesBase bc = Request.Browser;

                if (!bc.IsBrowser("FIREFOX"))
                {
                    downloadName = HttpUtility.UrlEncode(downloadName);
                }

                Response.Charset = "UTF-8";
                Response.ContentEncoding = Encoding.GetEncoding("GB2312");
                Response.ContentType = "application/vnd.ms-excel";
                this.HttpContext.Response.AddHeader("Content-Disposition", string.Format("attachment; filename={0}.xlsx", downloadName));
                this.HttpContext.Response.BinaryWrite(bytes);
            }
            return new EmptyResult();
        }

        public class ViewDataUploadFilesResult
        {
            public string openid { get; set; }
            public string name { get; set; }
            public string save_name { get; set; }
            public int size { get; set; }
            public string type { get; set; }
            public string url { get; set; }
            public string delete_url { get; set; }
            public string thumbnail_url { get; set; }
            public string delete_type { get; set; }
        }
    }
}

PowerNew/PowerNew/Views/ArticleInfo/Create.cshtml
@using PowerNew.Bll
@model PowerNew.Model.bjf_articleinfo

@{
    ViewBag.Title = "添加文章";
}

<div class="container">
    <div class="row" style="margin-top: 20px;">
        <div class="col-lg-6">
            <span style="font-size: 20px;margin-left: 5%"><i class="glyphicon glyphicon-plus"></i>@ViewBag.Title </span>
        </div>
        <div class="col-lg-6" style="">
            <button class="btn btn-info" data-loading-text="正在保存..." style="margin-left: 20px;" id="btnsave"><i class="glyphicon glyphicon-floppy-disk"></i>保存</button>
            <a class="btn btn-info" href="@Url.Action("Index")"><i class="glyphicon glyphicon-export"></i>返回</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-12" style="margin-top: 20px;">
            <form id="form1" class="form-horizontal" method="POST" action="@Url.Action("SubmitSave")">
                <div class="form-group">
                    <label class="col-sm-2 control-label">文章类型：</label>
                    <div class="col-sm-5 input-group">
                        @Html.DropDownList("parentid", SelectListCenter.GetArticleTypeOneSelectList(), new { @class = "form-control", @id = "parentid" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for=""><span class="f_req"></span>文章系列：</label>
                    <div class="col-sm-5 input-group">
                        @Html.DropDownList("typeid", SelectListCenter.GetArticleTypeTwoSelectList(), new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="title">文章标题：</label>
                    <div class="col-sm-5" style="margin-top: 5px;">
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                </div>
                <div id="imagefile" class="form-group">
                    <label class="col-sm-2 control-label" for="">主题图片：</label>
                    <div class="col-sm-7">
                        <input id="txt_imagefile" class="file-loading" type="file" accept=".jpg,.png" max="1" multiple="multiple">
                        <br>
                        <input id="ImageUrl" type="text" style="visibility: hidden;margin-top: -50px;" name="ImageUrl" value="" class="form-control">
                    </div>
                    <div class="col-sm-2">
                        <span class="help-block form-control-static f_req">限jpg、png格式,每张小于100K</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="">新闻内容：</label>
                    <div class="col-sm-5" style="margin-top: 5px;">
                        <script id="editor" name="Editor" type="text/plain" style="width: 800px;height:500px">

                        </script>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@Styles.Render("~/css/fileinput")

@Scripts.Render("~/js/fileinput")
<script type="text/javascript">
    $(function () {
        UE.getEditor('editor');
        //-------图片
        var strimg1 = null;
        $('#txt_imagefile').fileinput({
            language: 'zh',
            uploadUrl: '@Url.Action("UploadFiles", "File", new {area = ""})',
            allowedFileExtensions: ['png', 'jpg'],
            maxFilePreviewSize: 100,
            uploadAsync: true,
            initialPreview: [
                strimg1
            ],
            maxFileCount: 1
        });

        //----------------------图片
        $('.fileinput-remove-button', '#ImageUrl').click(function () {
            $("#ImageUrl").val('');
        });
        //删除图标回调
        $('#txt_imagefile').on('fileclear', function (event, data) {
            $("#ImageUrl").val('');
        });

        //异步请求回调获取返回值
        $('#txt_imagefile').on("fileuploaded", function (event, data) {
            var temp = "";
            var a = $("#ImageUrl").val();
            $.each(data.response, function (index, item) {
                temp += item.url;
            });
            a == "" ? a += temp : a += "," + temp;
            $("#ImageUrl").val(a);
        });

        $("#parentid").change(function () {
            var parentid = $(this).val();
            var url = "@Url.Action("GetTwoArticleType","ArticleType")";
            $.post(url,
                { parentid: parentid },
                function (result) {
                    $("#typeid").html(result);
                });
        });
        $("#btnsave").click(function () {
            $("#form1").validate({
                rules: {
                    //parentid: {
                    //    isparentid: true
                    //},
                    //typeid: {
                    //    istypeid: true
                    //},
                    title: {
                        required: true
                    },
                    ImageUrl: {
                        required: true
                    }
                },

                messages: {
                    //parentid: {
                    //    parentid: "文章类别不能为空"
                    //},
                    //typeid: {
                    //    typeid: true
                    //},
                    title: {
                        required: "文章系列不能为空."
                    },
                    ImageUrl: {
                        required: "请上传主题图片."
                    }
                },
                errorClass: "error",
                success: 'valid',
                unhighlight: function (element, errorClass, validClass) { //验证通过
                    $(element).tooltip('destroy').removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    if ($(element).next("div").hasClass("tooltip")) {
                        $(element).attr("data-placement", "right");
                        $(element).attr("data-original-title", $(error).text()).tooltip("show");
                    } else {
                        $(element).attr("title", $(error).text()).tooltip("show");
                    }
                },
                submitHandler: function () {
                    $("#btnsave").button('loading');
                    $("form:first").ajaxSubmit(function (result) {
                        if (result.state == 0) {
                            alert(result.msg);
                            $("#btnsave").button('reset');
                            window.location.href = "@Url.Action("Index")";
                        } else { alert(result.msg); $("#btnsave").button('reset'); }
                    });
                }
            });

            jQuery.validator.addMethod("isparentid", function (value, element) {
                value = parseInt(value);
                return this.optional(element) || value > 0;
            }, "请选择文章类别");

            jQuery.validator.addMethod("istypeid", function (value, element) {
                value = parseInt(value);
                return this.optional(element) || value > 0;
            }, "请选择文章系列");

            var a = $("#form1").serialize();
            alert(a);
            $("form:first").submit();

        });
    });

</script>

PowerNew/PowerNew/Views/ArticleInfo/Edit.cshtml
@using PowerNew.Bll
@model PowerNew.Model.bjf_articleinfo

@{
    ViewBag.Title = "编辑文章";
}
<div class="container">
    <div class="row" style="margin-top: 20px;">
        <div class="col-lg-6">
            <span style="font-size: 20px;margin-left: 5%"><i class="glyphicon glyphicon-plus"></i>@ViewBag.Title</span>
        </div>
        <div class="col-lg-6" style="">
            <button class="btn btn-info" data-loading-text="正在保存..." style="margin-left: 20px;" id="btnsave"><i class="glyphicon glyphicon-floppy-disk"></i>保存</button>
            <a class="btn btn-info" href="@Url.Action("Index")"><i class="glyphicon glyphicon-export"></i>返回</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-12" style="margin-top: 20px;">
            <form id="form1" class="form-horizontal" method="POST" novalidate="novalidate" action="@Url.Action("SubmitEdit")">
                <input name="ID" value="@Model.id" type="hidden" />
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="">文章类型：</label>
                    <div class="col-sm-5 input-group">
                        @Html.DropDownList("parentid", SelectListCenter.GetArticleTypeOneSelectList(Model.parentid), new { @class = "form-control", @id = "parentid" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for=""><span class="f_req"></span>文章系列：</label>
                    <div class="col-sm-5 input-group">
                        @Html.DropDownList("typeid", SelectListCenter.GetArticleTypeTwoSelectList(Model.parentid, Model.typeid), new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="title">文章标题：</label>
                    <div class="col-sm-5" style="margin-top: 5px;">
                        <input type="text" class="form-control" id="title" name="title" value="@Model.title">
                    </div>
                </div>
                <div id="imagefile" class="form-group">
                    <label class="col-sm-2 control-label" for="">主题图片：</label>
                    <div class="col-sm-7">
                        <input id="txt_imagefile" class="file-loading" type="file" accept=".jpg,.png" max="1" multiple="multiple">
                        <br>
                        <input id="ImageUrl" type="text" style="visibility: hidden;margin-top: -50px;" name="ImageUrl" value="" class="form-control">
                    </div>
                    <div class="col-sm-2">
                        <span class="help-block form-control-static f_req">限jpg、png格式,每张小于100K</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="">新闻内容：</label>
                    <div class="col-sm-5" style="margin-top: 5px;">
                        <script id="editor" name="Editor" type="text/plain" style="width: 800px;height:500px">
                            @Html.Raw(Model.content)
                        </script>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@Styles.Render("~/css/fileinput")

@Scripts.Render("~/js/fileinput")
<script type="text/javascript">
    UE.getEditor('editor');

    //-------图片
    var strimg1 = "@Model.photourl" != null ? "<img src='@Model.photourl' style='width: 250px; height: 220px;' />" : null;
    $('#txt_imagefile').fileinput({
        language: 'zh',
        uploadUrl: '@Url.Action("UploadFiles", "File", new {area = ""})',
        allowedFileExtensions: ['png', 'jpg'],
        maxFilePreviewSize: 100,
        uploadAsync: true,
        initialPreview: [
            strimg1
        ],
        maxFileCount: 1
    });

    //----------------------图片
    $('.fileinput-remove-button', '#ImageUrl').click(function () {
        $("#ImageUrl").val('');
    });
    //删除图标回调
    $('#txt_imagefile').on('fileclear', function (event, data) {
        $("#ImageUrl").val('');
    });

    //异步请求回调获取返回值
    $('#txt_imagefile').on("fileuploaded", function (event, data) {
        var temp = "";
        var a = $("#ImageUrl").val();
        $.each(data.response, function (index, item) {
            temp += item.url;
        });
        a == "" ? a += temp : a += "," + temp;
        $("#ImageUrl").val(a);
    });


    $("#btnsave").click(function () {
        $("#form1").validate({
            rules: {
                //parentid: {
                //    isparentid: true
                //},
                //typeid: {
                //    istypeid: true
                //},
                title: {
                    required: true
                },
                ImageUrl: {
                    required: true
                }
            },

            messages: {
                //parentid: {
                //    parentid: "文章类别不能为空"
                //},
                //typeid: {
                //    typeid: true
                //},
                title: {
                    required: "文章系列不能为空."
                },
                ImageUrl: {
                    required: "请上传主题图片."
                }
            },
            errorClass: "error",
            success: 'valid',
            unhighlight: function (element, errorClass, validClass) { //验证通过
                $(element).tooltip('destroy').removeClass(errorClass);
            },
            errorPlacement: function (error, element) {
                if ($(element).next("div").hasClass("tooltip")) {
                    $(element).attr("data-placement", "right");
                    $(element).attr("data-original-title", $(error).text()).tooltip("show");
                } else {
                    $(element).attr("title", $(error).text()).tooltip("show");
                }
            },
            submitHandler: function () {
                $("#btnsave").button('loading');
                $("form:first").ajaxSubmit(function (result) {
                    if (result.state == 0) {
                        alert(result.msg);
                        $("#btnsave").button('reset');
                        window.location.href = "@Url.Action("Index")";
                    } else { alert(result.msg); $("#btnsave").button('reset'); }
                });
            }
        });
        var a = $("#form1").serialize();
        alert(a);
        $("form:first").submit();
    });
</script>

PowerNew/PowerNew/Views/ArticleInfo/Index.cshtml
@model PowerNew.Common.PagerResult<PowerNew.Model.bjf_articleinfo>
@{
    var index = Model.Index;
    var param = ViewBag.param;
}
<div class="" style="width:100%;margin:0 auto">
    <div class="form-group">
        <div><h3 class="col-sm-2" style="margin-top: 5px;"><i class="glyphicon glyphicon-tag"></i>文章列表</h3></div>
        <div class="form-group" style="margin-top: 10px;">
            <a class="btn btn-info" href="@Url.Action("Index")"><i class="glyphicon glyphicon-refresh"></i>刷新</a>
            <a class="btn btn-info" href="@Url.Action("Create")"><i class="glyphicon glyphicon-plus"></i>添加</a>
        </div>
        <hr>
    </div>
    <form id="formQuery" method="get" action="@Url.Action("Index")">
        <div class="form-group">
            <label class="col-sm-2 control-label" style="line-height: 43px">文章标题：</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" value="@param.title" name="blockname">
            </div>
        </div>
        <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-search"></i>查询</button>
        <button class="btn btn-warning" type="button" id="btnclear"><i class="glyphicon glyphicon-trash"></i>清空</button>
    </form>
    <table id="table-area" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>序号</th>
                <th>文章标题</th>
                <th>阅读次数</th>
                <th>作者</th>
                <th>最后更新时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody id="thisbody">
            @foreach (PowerNew.Model.bjf_articleinfo item in Model.DataList)
            {
                index++;
                <tr>
                    <td>@index</td>
                    <td>@item.title</td>
                    <td>@item.readcount</td>
                    <td>@item.userid</td>
                    <td>@item.updatetime</td>
                    <td>
                        <a class="btn btn-link btn-xs" href="@Url.Action("Edit", new {id = item.id})">修改</a><a class="btn btn-link btn-xs" onclick="IsDelete(@item.id)">删除</a>

                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>
<div class="form-group" style="width: 60%; float: right">
    <div class="col-sm-8" style="text-align:right">@Html.Raw(Model.PagerHtml())</div>
    <span class="col-sm-2" style="line-height: 81.5px">共 @Model.Total 条</span>
</div>
<script type="text/javascript">

    function IsDelete(id) {
        if (!confirm("是否要删除该条信息？")) {
            return;
        }
        var url = "@Url.Action("Delete")";
        $.post(url, { id: id }, function (result) {
            if (result.state == 0) {
                alert(result.msg);
                window.location.reload();
            } else {
                alert(result.msg);
            }
        });
    }

    $(function () {
        $("#btnclear").click(function () {
            $("#formQuery :input").each(function () {
                $(this).val("");
            });
        });
    });


</script>