PowerNew/PowerNew/Controllers/Blog/Blog/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using PowerNew.Bll;

namespace PowerNew.Controllers
{
    public partial class BlogController : Controller
    {
        public ActionResult Index()
        {
            //var cityName = RouteData.Values["company"];
            //if (!cityName.Equals("www"))
            //{
            //    return View("Login");
            //}
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetArticleList(QueryArticleInfo query)
        {
            var list = ArticleInfoManager.GetInstance().GetBlogPageList(query);
            var data = list.DataList.Select(m => new ArticleInfoItem()
            {
                id = m.id,
                parentid = m.parentid,
                title = m.title,
                typeid = m.typeid,
                photourl = m.photourl,
                updatetime = m.updatetime,
                readcount = m.readcount,
                content = m.content,
                createtime = m.createtime,
                UserName = UserManager.GetInstance().GetItemById(m.userid).username,
            });
            return Json(new { data = data, pagehtml = list.PagerHtml(), index = list.Index });
        }
        /// <summary>
        /// 右边通用分布视图
        /// </summary>
        /// <returns></returns>
        public ActionResult GetRightView()
        {
            //获取管理员用户
            ViewBag.UserInfo = UserManager.GetInstance().SelectOne(p => p.username == "admin");
            //获取文章分类
            var list = ArticleTypeManager.GetInstance().SelectList(m => m.isdelete == false);
            var zNodes = list.Select(m => new NodeInfo()
            {
                id = m.id,
                pId = m.parentid,
                name = m.title,
                open = true
            });
            ViewBag.zNodes = JsonConvert.SerializeObject(zNodes);
            return PartialView();
        }


        public ActionResult SearchArticle()
        {
            var articleInfoList = new List<ArticleInfoController.ArticleInfo>();

            return View();
        }

        public ActionResult Detail(int id)
        {
            var model = ArticleInfoManager.GetInstance().GetModel(id);
            ViewBag.UserName = "";
            if (model != null)  //阅读次数+1
            {
                model.readcount += 1;
                ArticleInfoManager.GetInstance().Update(model);
                ArticleInfoManager.GetInstance().Save();
                ViewBag.UserName = UserManager.GetInstance().GetItemById(model.userid).username;
            }
            
            return View(model);
        }

        public class NodeInfo
        {
            public int id { get; set; }
            public int pId { get; set; }
            public string name { get; set; }
            public bool open { get; set; }
        }
    }
}

PowerNew/PowerNew/Controllers/VisitView/VisitViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PowerNew.Bll;
using PowerNew.Filter;

namespace PowerNew.Controllers.VisitView
{
    public class VisitViewController : Controller
    {
        [IsLoginAuthorize]
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GetParam()
        {
            try
            {
                var x = LoginLogManager.GetInstance().GetXArry();
                var y = LoginLogManager.GetInstance().GetYArry();

                //用于饼状图表
                var name = LoginLogManager.GetInstance().GetYList();
                var info = LoginLogManager.GetInstance().GetListShowInfo();

                return Json(new { state = 0, x = x, y = y, name = name, info = info });
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        public void Chart2()
        {
            new Chart(width: 600, height: 400, theme: ChartTheme.Yellow)
                .AddTitle("人员流动情况")

                .AddSeries(name: "Employee",
                           chartType: "line",
                xValue: new[] { "一月份", "二月份", "三月份", "四月份", "五月份", "六月份", "七月份", "八月份", "九月份" },
                yValues: new[] { "2", "6", "4", "5", "3", "4", "9", "2", "5" }

                )

                .AddSeries(name: "Mall"
                    , chartType: "Column"
                    , xValue: new[] { "A", "B", "C", "D", "E", "F", "G", "H", "I" }
                    , yValues: new[] { 4, 5, 8, 1, 6, 8, 4, 3, 6 })

                .Write();
        }
    }
}

PowerNew/PowerNew/Views/Shared/_BlogFooter.cshtml
<style>
    .shakeimage {
        position: relative;
        left: 100px;
    }

    #fot {
        color: #808181;
    }

        #fot a {
            cursor: pointer;
            color: #808181;
            border-radius: 20px 20px 20px 20px;
        }

            #fot a:hover {
                background: none;
                color: white;
                text-decoration-color: white;
                text-decoration-line: underline;
            }
</style>
<footer class="blog-footer" style="margin-top: 100px;">
    <div class="am-g" style="background-color: #444546;">
        <div class="am-u-md-8 am-input-group" id="fot">

            <div class="am-u-md-4">
                <ul class="am-nav">
                    <li class="am-nav-header"><a>前端网站</a></li>
                    <li><a href="http://www.bootcss.com/" target="_blank">Bootstrap</a></li>
                    <li><a href="http://amazeui.org/" target="_blank">Amaze UI</a></li>
                    <li><a href="http://www.angularjs.net.cn/" target="_blank">Angular.js</a></li>
                </ul>
            </div>
            <div class="am-u-md-4">
                <ul class="am-nav">
                    <li class="am-nav-header"><a>技术网站</a></li>
                    <li><a href="http://www.runoob.com" target="_blank">菜鸟联盟</a></li>
                    <li><a href="http://www.shouce.ren/" target="_blank">手册网</a></li>
                    <li><a href="https://www.cnblogs.com/" target="_blank">博客园</a></li>
                </ul>
            </div>
            <div class="am-u-md-4">
                <ul class="am-nav">
                    <li class="am-nav-header"><a>问题交流</a></li>
                    <li><span class="am-icon-qq" style="cursor: pointer;">QQ：806078508</span></li>
                </ul>
            </div>
        </div>
        <div class="am-u-md-2">
            <div style="margin-top: 30px;">
                <img style="border-radius: 20px 20px 20px 20px;" src="~/Image/Wechat.png" width="100" height="100" title="记得关注我哦" class="shakeimage" onmouseover="shake(this,'onmouseout')" />
            </div>
        </div>
        <div class="am-u-md-2">
        </div>
    </div>
    <p style="background-color: white; height: 50px; margin-bottom:auto">
        <a style="color: gray;" href="@Url.Action("Index", "Blog")">Aaron‘s Blog</a><br />
        <small><a style="color: gray" href="@Url.Action("Index", "Blog")">© 2016 Aaron‘s Blog · Designed by Aaron</a></small>
    </p>
</footer>
<script type="text/javascript">
    var typ = ["marginTop", "marginLeft"], rangeN = 5, timeout = 5;

    function shake(o, end) {
        var range = Math.floor(Math.random() * rangeN);
        var typN = Math.floor(Math.random() * typ.length);
        o["style"][typ[typN]] = "" + range + "px";
        var shakeTimer = setTimeout(function () { shake(o, end) }, timeout);
        o[end] = function () { clearTimeout(shakeTimer) };
    }
</script>

PowerNew/PowerNew/Views/Shared/_BlogHeader.cshtml
@using System.Configuration
<header class="am-topbar" style="position:fixed; top: 0; width: 100%; z-index: 999; background-color: rgba(255, 255, 255, 0.9); ">
    <h1 class="am-topbar-brand">
        <a href="@Url.Action("index", "Home")">Aaron's blog</a>
    </h1>
    <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
        <ul id="navigateMenu" class="am-nav am-nav-pills am-topbar-nav">
            <li id="navigateIndex"><a href="@Url.Action("index", "Blog")">首页</a></li>
            <li id="navigateMessageBoard"><a href="@Url.Action("MessageBoard", "Blog")">留言板</a></li>
            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    更多 <span class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="@Url.Action("Login", "Login")">后台管理</a></li>
                    <li><a href="#">关于字体</a></li>
                </ul>
            </li>
        </ul>
        <script>
            $(function () {
                //设置导航栏菜单切换效果
                //当前地址是首页
                if ('@Request.Url' == "@ConfigurationManager.AppSettings["domainName"]/") {
                    $("#navigateIndex").attr("class", "am-active");
                }
                //当前地址是留言板
                if ('@Request.Url'.indexOf("MessageBoard") != -1) {
                    $("#navigateMessageBoard").attr("class", "am-active");
                }
            });
        </script>
        <form id="ArticleSearchForm" class="am-topbar-form am-topbar-left am-form-inline am-topbar-right" role="search" method="POST" action="@Url.Action("SearchArticle", "Blog")">
            <div class="am-form-group">
                <input id="searchStr" name="searchStr" type="text" class="am-form-field am-input-sm" placeholder="搜索文章">
                <input type="hidden" name="type" value="articletitle" />
                <input type="hidden" name="pageIndex" value="1" />
            </div>
            <button id="btnSearch" type="button" class="am-btn am-btn-default am-btn-sm">搜索</button>
            <script>
                $(function () {
                    $("#btnSearch").click(function () {
                        if ($("#searchStr").val().length <= 0) {
                            location.href = "@Url.Action("Index", "Blog")";
                        }
                        $("#ArticleSearchForm").submit();
                    });
                });
            </script>
        </form>
    </div>
</header>

PowerNew/PowerNew/Views/Shared/_BlogLayout.cshtml
@using System.Configuration
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Aaron's blog-我在这里等风也等你</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta name="description" itemprop="description" content="Aaron的个人博客,博主喜欢编程,希望能和大家成为好朋友 >.<" />
    <link rel="alternate icon" type="image/png" href="/Content/Image/icon.jpg">
    <link rel="stylesheet" href="/Content/assets/css/amazeui.min.css" />
    <link rel="stylesheet" href="~/Content/assets/css/Blog.css" />
    <link rel="stylesheet" href="~/Content/Blog/Base.css" />
    <script src="/Content/assets/js/jquery.min.js"></script>
    <script src="/Content/assets/js/amazeui.min.js"></script>
    <script src="~/Scripts/Blog/Base.js"></script>
    <script src="~/Content/layer/layer.js"></script>
    <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
    <script src="/Content/assets/js/amazeui.ie8polyfill.min.js"></script>

</head>
<body>
    @Html.Partial("_BlogHeader")
    <div class="am-g am-g-fixed blog-g-fixed">
        @Html.Partial("_BlogMsg")
        <div id="ContentBodyDiv" style="border-radius: 20px 20px 20px 20px; margin-top: 10px; background-color: aliceblue" class="am-u-md-8 ">
            @RenderBody()
        </div>
        @{
            Html.RenderAction("GetRightView", "Blog");
        }
    </div>
    @Html.Partial("_BlogMiddle")
    @Html.Partial("_BlogFooter")
    <!--效果-->
    @*<div id="xiaomaiDiv" class="xiaomai">
            <img style="width: 50px" src="~/Content/Image/xiaomai.png" />
            <script>
                $(function () {
                    $("#xiaomaiDiv").mouseover(function () {
                        $(this).animate({ bottom: "1.8px" }, 700);
                    });
                    $("#xiaomaiDiv").mouseout(function () {
                        $(this).animate({ bottom: "0px" }, 100);
                    });
                });
            </script>
        </div>*@
    <!--效果-->
    <!--回到顶部-->
    <div id="back-to-top" class="am-hide-sm-only" data-am-smooth-scroll="{speed: 1000}">
        <script>
            $(function () {
                $(window).scroll(function () {
                    //滚动条到达页面一半的时候
                    if ($(document).scrollTop() >= ($(document).height() - $(window).height()) / 2) {
                        //改变height属性 触发css的transition的效果
                        $("#back-to-top").css("height", "900px"); //图片高度就是900px 小了显示不全
                    }
                    //滚动条不到页面一半的时候
                    if ($(document).scrollTop() <= ($(document).height() - $(window).height()) / 2) {
                        //改变height属性 触发css的transition的效果
                        $("#back-to-top").css("height", "-900px");
                    }
                });
            });
        </script>
    </div>
</body>
</html>

PowerNew/PowerNew/Views/Shared/_BlogMiddle.cshtml
<div class="am-g am-g-fixed blog-g-fixed" style="margin-top: 20px;">
    <div style="width: 48%; float: left">
        <div class="am-panel-group">
            <section class="am-panel am-panel-default">
                <div class="am-panel-hd">前端技术<span style="float: right"></span></div>
                <div class="am-panel-bd">
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div style="margin-left: 4%;width: 48%;float: left">
        <div class="am-panel-group">
            <section class="am-panel am-panel-default">
                <div class="am-panel-hd">后端技术<span style="float: right"></span></div>
                <div class="am-panel-bd">
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                    <div class="am-g" style="text-align: center; font-size: 15px">
                        <div class="am-panel-group">
                            <div class="am-u-sm-8" style="text-align: left;">nice to meet you</div>
                            <div class="am-u-sm-4" style="text-align: right;">2017-01-05</div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

PowerNew/PowerNew/Views/Shared/_BlogMsg.cshtml
<style>
    div, ul, li {
        margin: 0;
        padding: 0;
    }
    /*先初始化一下默认样式*/
    a {
        text-decoration: none;
        color: #222;
    }

    .notice {
        width: 50%;
        font-size: 16px;
        line-height: 50px;
        height: 50px;
        overflow: hidden;
        margin-left: 10px;
    }


        .notice ul li {
            list-style: none;
            line-height: 50px;
            display: block;
            margin-left: 80px;
        }


        .notice a {
            float: left;
            display: inline-block;
            width: 70%;
            margin-left: 20px;
            text-decoration: none;
        }


            .notice a:first-child {
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }


            .notice a span {
                color: #999;
                font-size: 12px;
                margin-right: 10px;
            }


    .more {
        position: absolute;
        line-height: 50px;
        font-size: 12px;
        color: #ff9900;
    }


    .new-notice {
        margin-left: 5px;
        position: absolute;
        line-height: 50px;
        color: #228b22;
        font-size: 18px;
        font-weight: bolder;
        font-family: 微软雅黑;
    }
</style>
<div style="border-radius: 20px 20px 20px 20px; height: 50px; margin-top: 70px; background-color: aliceblue">

    <span class="am-icon-volume-up new-notice" style="float: left">最新公告:</span>
    <div class="notice" style="float: left">
        <ul>
            <li>
                <a href="#">
                    nice to meet you
                </a>
            </li>
            <li>
                <a href="#">
                    我的博客马上就要上线了，请大家持续关注哦！
                </a>
            </li>
        </ul>
    </div>
    <a href="#" class="more" style="float: left">更多公告>></a>
    @*<label style="line-height: 50px; margin-left: 10px;"> </label>*@
    @*<span class="am-icon-volume-up"></span><span style="margin-left: 10px;color:red">公告：好消息！！！！</span>*@
    <!-- #region 滚动效果 -->
    @*<script language=JavaScript>
            //[Step1]: 在此能够更改滚动文本的宽度
            var MarqueeWidth = 500;
            //[Step2]: 这里可以改变滚动文本的高度
            var MarqueeHeight = 10;
            //[Step3]: 在此能够修改文本滚动的速度，数值大，滚动快 -->
            var speed = 7;
            // [Step4]: 这里可以更改滚动文本的颜色 -->
            // [Step5]: 在此能够修改滚动文本的内容 -->
            var MarqueeMessage =
                '<font face="Arial"  color=#FF0066><strong><big>公告：好消息！！！！</big></strong></font>';
            document.write('<marquee scrollAmount=' +
                speed +
                ' style="width:' +
                MarqueeWidth +
                '">' +
                MarqueeMessage +
                '</marquee>');
            function RegLayers() {
                if (document.layers) {
                    setTimeout("window.onresize=RegLayers", 450);
                    intializemarquee();
                }
            }

            function intializemarquee() {
                document.MarqueeText001.document.MarqueeText002.document.write('<nobr>' +
                    MarqueeMessage +
                    '</nobr>');
                document.MarqueeText001.document.MarqueeText002.document.close();
                thelength = document.MarqueeText001.document.MarqueeText002.document.width;
                ScrollText();
            }


            function ScrollText() {
                if (document.MarqueeText001.document.MarqueeText002.left >= thelength * (-1)) {
                    document.MarqueeText001.document.MarqueeText002.left -= speed;
                    setTimeout("ScrollText()", 100);
                } else {
                    document.MarqueeText001.document.MarqueeText002.left = MarqueeWidth;
                    ScrollText();
                }
            }

            window.onload = RegLayers;
        </script>*@
    <!-- #endregion -->

</div>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    function noticeUp(obj, top, time) {
        $(obj).animate({
            marginTop: top
        },
            time,
            function () {
                $(this).css({ marginTop: "0" }).find(":first").appendTo(this);
            });
    };

    $(function () {
        // 调用 公告滚动函数
        setInterval("noticeUp('.notice ul','-35px',500)", 4000);
    });
</script>

PowerNew/PowerNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @*@using StackExchange.Profiling
        @MiniProfiler.RenderIncludes()*@
    <title>Aaron's blog-----后台</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Image/favicon.ico.png" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=2.0, user-scalable=yes" />
    <link rel="alternate icon" type="image/png" href="/Image/ali123.png">
    @Html.Partial("_PartHeader")     @*-----引入js和css*@
</head>

<body>
    <div class="header">
        @Html.Partial("_PartTop") @*-----顶部导航区*@
    </div>

    <div class="content">
        <div class="form-group main">
            @Html.Partial("_PartLeft") @*-----左边导航区*@
            <div class="col-sm-10" style="height: 100%; max-height: 800px; background-color:ghostwhite; overflow: auto;overflow-x:hidden">
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="footer">
        <div style="text-align: center; background-color: lightblue;color: #008080">Aaron's Project</div>  @*-----底部*@
    </div>
</body>
</html>

PowerNew/PowerNew/Views/Shared/_PartHeader.cshtml
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Css/LayoutIndex.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@*<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/messages_zh.js"></script>
<script src="~/Scripts/jquery.form.js"></script>



@*@Styles.Render("~/css/common")

@Scripts.Render("~/js/common")*@

PowerNew/PowerNew/Views/Shared/_PartTop.cshtml
<style>
    .topdiv, .topdiv div {
        height: 70px;
        margin: 0 auto;
    }

    .nav li a {
        color: white;
    }

        .nav li a:hover {
            background: none;
            outline: none;
            color: blueviolet;
        }

    .nav li ul a:hover {
        color: blueviolet;
    }
</style>
<div class="form-group topdiv">
    <div id="div2" class="col-sm-2" style="text-align: center">
        <a href="@Url.Action("Index","Blog")" target="_blank"><img src="~/Image/newblog1.png" style="width: 90px; height: 60px;padding-top: 10px" /></a>
    </div>
    <div class="col-sm-1" style="border-left: 2px dashed white;padding:10px 0px 10px 0px">
        @*<img src="~/Image/xuline.png" style="padding-top: 20px;" />*@
    </div>
    <div class="col-sm-3">
        <h3 style="color: white; font-weight: lighter">Aaron's Blog</h3>
    </div>
    <div class="col-sm-6">
        <ul class="nav" id="topnav" style="float: right">
            <li class="dropdown">
                <a id="usera" class="btn dropdown-toggle" data-toggle="dropdown" style="cursor: pointer"><i class="glyphicon glyphicon-user"></i>@Session["username"]&nbsp;&nbsp;<i name="downa" class="glyphicon glyphicon-chevron-down"></i></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation" class="dropdown-header" style="width: 100%; cursor: pointer"><a style="color: red" role="menuitem" tabindex="-1"><i class="glyphicon glyphicon-edit"></i>修改密码</a></li>
                    <li role="presentation" style="width: 100%; cursor: pointer"><a style="color: red" role="menuitem" tabindex="-1" href="@Url.Action("SignOut", "Login")"><i class="glyphicon glyphicon-share"></i>退出登录</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Index", "VisitView")"><i class="glyphicon glyphicon-volume-up"></i>站点访问</a></li>
        </ul>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#usera").click(function () {
            if ($(this).find("i[name='downa']").hasClass("glyphicon-chevron-down")) {
                $(this).find("i[name='downa']").removeClass("glyphicon-chevron-down");
                $(this).find("i[name='downa']").addClass("glyphicon-chevron-up");
            } else {
                $(this).find("i[name='downa']").removeClass("glyphicon-chevron-up");
                $(this).find("i[name='downa']").addClass("glyphicon-chevron-down");
            }
        });
    });
</script>