PowerNew/PowerNew/Controllers/Blog/ArticleType/ArticleTypeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using PowerNew.Bll;
using PowerNew.Model;

namespace PowerNew.Controllers
{

    public partial class ArticleTypeController : BaseController
    {
        // GET: ArticleType
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Tree()
        {
            var treeNode = new ProductCategoryTreeNode();
            //最底层的分类
            var rootList = ArticleTypeManager.GetInstance().GetRootList(0);
            foreach (var item in rootList)
            {
                this.LoadMenuTreeNode(item, treeNode);
            }
            return Json(treeNode, JsonRequestBehavior.AllowGet);
        }

        private void LoadMenuTreeNode(bjf_articletype item, ProductCategoryTreeNode treeNode)
        {
            if (item == null)
            {
                return;
            }
            var currentNode = new ProductCategoryTreeNode();
            currentNode.Id = item.id;
            currentNode.key = item.id.ToString();
            currentNode.expanded = true;
            currentNode.folder = false;
            currentNode.title = item.title;
            currentNode.ParentId = item.parentid;
            if (item.parentid == 0)
            {
                currentNode.IsAddButtonForNextLevel = true;
            }
            currentNode.SortCode = item.id;
            treeNode.children.Add(currentNode);
            List<bjf_articletype> groupmentList = ArticleTypeManager.GetInstance().SelectList(m => m.isdelete == false && m.parentid == item.id);
            if (groupmentList.Count > 0)
            {
                foreach (var childItem in groupmentList)
                {
                    this.LoadMenuTreeNode(childItem, currentNode);
                }
            }
        }

    }


    public class ProductCategoryTreeNode : FancyTreeNode
    {
        public ProductCategoryTreeNode()
        {
            SortCode = 0;
            this.expanded = true;
            this.lazy = false;

            this.Level = 0;

        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string CategoryName { get; set; }

        public string Code { get; set; }

        public int SortCode { get; set; }

        public int Level { get; set; }

        public bool IsAddButtonForCategory { get; set; }

        public bool IsAddButtonForSeries { get; set; }
        public bool IsAddButtonForNextLevel { get; set; }

    }

    public class FancyTreeNode
    {
        public FancyTreeNode()
        {
            this.children = new List<FancyTreeNode>();
            this.expanded = false;
            this.lazy = false;
        }

        public long ID { get; set; }
        public string NodeType { get; set; }
        public int ParentId { get; set; }
        public string key { get; set; }
        public string title { get; set; }
        public bool folder { get; set; }
        public bool lazy { get; set; }
        public bool expanded { get; set; }
        public List<FancyTreeNode> children { get; set; }

        public bool hideCheckbox { get; set; }
        public bool unselectable { get; set; }


    }
}

PowerNew/PowerNew/Views/ArticleType/Edit.cshtml
@model PowerNew.Model.bjf_articletype
@{
    var title = Model.id == 0 ? "添加分类" : "修改分类";
}
<div class="container">
    <div class="row">
        <div class="form-group" style="margin-top: 20px;">
            <span style="font-size: 20px;margin-left: 5%"><i class="glyphicon glyphicon-plus"></i>@title</span>
            <a class="btn btn-info" id="btnsavetype" data-loading-text="正在保存..." style="margin-left: 40%"><i class="glyphicon glyphicon-floppy-disk"></i>保存</a>
            <a class="btn btn-info" href="@Url.Action("Index")"><i class="glyphicon glyphicon-export"></i>返回</a>
        </div>
    </div>

    <hr class="hr1">
    <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-12" style="margin-top: 10px;">
            <form id="form1" class="form-horizontal" method="POST" action="@Url.Action("SubmitSave","ArticleType")">
                <input type="hidden" name="id" value="@Model.id" />
                <input type="hidden" name="parentid" value="@Model.parentid" />
                @if (Model.parentid > 0)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label"><span class="f_req"></span>父类名称：</label>
                        <div class="col-sm-5">
                            <input type="text" class="form-control" readonly="readonly" value="@ViewBag.ParentName">
                        </div>
                        <div class="col-sm-4">
                            <span class="help-block form-control-static"></span>
                        </div>
                    </div>
                }
                <div class="form-group">
                    <label class="col-sm-2 control-label"><span class="f_req">*</span>分类名称：</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" value="@Model.title" name="title">
                    </div>
                    <div class="col-sm-4">
                        <span class="help-block form-control-static"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="comment">备注：</label>
                    <div class="col-sm-5">
                        <textarea class="form-control" id="comment" name="comment">@Model.comment</textarea>
                    </div>
                    <div class="col-sm-4">
                        <span class="help-block form-control-static"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#btnsavetype").click(function () {
        $("#form1").validate({
            rules: {
                title: {
                    required: true
                }
            },
            messages: {
                title: {
                    required: "分类名称不能为空."
                }
            },
            errorClass: "error",
            success: 'valid',
            unhighlight: function (element, errorClass, validClass) { //验证通过
                $(element).tooltip('destroy').removeClass(errorClass);
            },
            errorPlacement: function (error, element) {
                if ($(element).next("div").hasClass("tooltip")) {
                    $(element).attr("data-placement", "right");
                    $(element).attr("data-original-title", $(error).text()).tooltip("show");
                } else {
                    $(element).attr("title", $(error).text()).tooltip("show");
                }
            },
            submitHandler: function () {
                $("#btnsavetype").button('loading');
                $("form:first").ajaxSubmit(function (result) {
                    if (result.state == 0) {
                        alert(result.msg);
                        $("#btnsave").button('reset');
                        window.location.href="@Url.Action("Index")";
                    } else { alert(result.msg); $("#btnsavetype").button('reset'); }
                });
            }
        });
        $("form:first").submit();

    });
</script>

PowerNew/PowerNew/Views/ArticleType/Index.cshtml
@model PowerNew.Common.PagerResult<PowerNew.Model.bjf_menu>
@{
    ViewBag.Title = "博客文章分类";
}

<link href="~/Content/jquery.fancytree/skin-win8/ui.fancytree.css" rel="stylesheet" />
<style type="text/css">
    .table td {
        text-align: left;
    }

        .table td.alignCenter {
            text-align: center;
        }

    span.fancytree-icon {
        display: none;
    }
</style>
<div class="" style="width:100%;margin:0 auto">
    <div class="form-group">
        <div><h3 class="col-sm-2" style="margin-top: 5px;"><i class="glyphicon glyphicon-tag"></i>@ViewBag.Title</h3></div>
        <div class="form-group" style="margin-top: 10px;">
            <a class="btn btn-info" href="@Url.Action("Index")"><i class="glyphicon glyphicon-refresh"></i>刷新</a>
            <a class="btn btn-info" href="@Url.Action("Create")"><i class="glyphicon glyphicon-plus"></i>添加</a>
        </div>
        <hr>
    </div>

    <div id="table-category" class="table-responsive">
        <table id="treetable" class="table table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>分类名称</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div id="showmsg"></div>
    <script id="NodeList" type="text/x-jsrender">
        <a class="btn btn-xs btn-link" href="@Url.Action("Edit")?id={{:id}}" onclick="showBox(this); return false;">编辑</a>
        <a id={{:id}} class="btn btn-xs btn-link" onclick="deleteNode(this); return false;">删除</a>
    </script>
</div>

@Scripts.Render("~/js/jqueryui")
@Scripts.Render("~/js/jsrender")
<script type="text/javascript">
    function deleteNode(obj) {
        var id = $(obj).attr('id');
        if (id == "") {
            alert("参数值不能为空！");
            return;
        }
        $.post("@Url.Action("IsParent")", { id: id }, function (result) {
            if (result.state === 0) {   //0表示子类
                if (!window.confirm("确定要删除吗？")) return;
                Delete(id);
            } else {
                if (!window.confirm("该类是父类，删除后对应子类也要删除，确定要删除吗？")) return;
                Delete(id);
            }
        });
    }

    function reloadTreeTable() {
        var url = "@Url.Action("Tree")";

        try {
            $("#treetable").fancytree("destroy"); //先销毁
        } catch (e) {
        }

        $("#treetable").fancytree({
            extensions: ["table"],
            clickFolderMode: 1,
            checkbox: false,
            table: {
                indentation: 20,
                nodeColumnIdx: 1
            },
            source: {
                url: url
            },

            lazyload: function (e, data) {

            },
            renderColumns: function (e, data) {
                var node = data.node;
                var $tdList = $(node.tr).find(">td");
                $tdList.eq(0).text(node.getIndexHier()).addClass("alignLeft");
                $tdList.eq(1).text(node.data.title).addClass("alignLeft");
                var id = node.data.Id;
                var parentId = node.data.ParentId;
                var isShowButton = node.data.IsAddButtonForNextLevel;
                var addUrl = '@Url.Action("Create")';
                var btnAddHtml = "";
                if (isShowButton) {
                    btnAddHtml = "<a href='" + addUrl + "?parentid=" + id + "' class='btn btn-xs btn-link' >添加下级</a>";
                } else {
                    btnAddHtml = "<a href='#'></a>";
                }
                var html = $("#NodeList").render({ id: id, parentId: parentId, isShowButton: isShowButton, btnAddHtml: btnAddHtml });
                $tdList.eq(2).html(html + btnAddHtml);
                $tdList.eq(2).addClass("alignLeft");
            }
        });
    }

    function SetBoxFinished() {
        $.colorbox.close();
        reloadTreeTable();
    }

    //加载树类型
    $(function () {
        reloadTreeTable();
    });


    //删除
    function Delete(id) {
        var url = "@Url.Action("Delete")?id=" + id;
        $.post(url, function (data) {
            if (data.state === 1) {
                alert(data.msg);
                reloadTreeTable();
            } else {
                alert(data.msg);
            }
        });
    }

</script>